### ISSUE TITLE
changeZoomLevel() - doesn't render animation?

### ISSUE THREAD

**Issue by zhagan** [KensingtonTech/ng2-panzoom#1]
I'm calling this function from the api like so:

let transXY = {x:500, y:500};
this.panZoomAPIImage.changeZoomLevel( 2.0, transXY);

I have replaced the variables with literals. but the view doesn't render.

If I call:

 this.panZoomAPIImage.zoomIn(transXY);

The image zooms - what have I got wrong or is it a bug? 

Thanks,
Zack

**Comment by KensingtonTech** [comment]
This sounds like a bug.  I’ll have a look soon.

**Comment by KensingtonTech** [comment]
I've located the issue and time permitting, should have a fix out sometime this week.

**Comment by zhagan** [comment]
Awww some thanks! Are you in Denver? I'll bring you a beer!

**Comment by KensingtonTech** [comment]
Indeed, I am.  I would be happy to drink your beer :)

The issue should be resolved.  Give it a go now.

**Comment by KensingtonTech** [comment]
Hi @zhagan - were you able to give it a go?

**Comment by zhagan** [comment]
It did, thank you, I'm traveling internationally at the moment with very
little internet, sry for the late reply
