### ISSUE TITLE
Input textbox not taking focus

### ISSUE THREAD

**Issue by kranthitechie** [KensingtonTech/ng2-panzoom#10]
Hi there, 

I just added pan-zoom over an element that has some textboxes. After adding, the pan, zoom works as expected, but the input textbox does not gain focus, and I am not able to enter anything in it.

**Comment by KensingtonTech** [comment]
Apologies for not responding sooner. I don’t believe this is something that can be fixed.  There are two divs which get overplayed on top of your content. When you click, you are also activating the pan functionality.  So the overlay divs are blocking the click and focus functionality on your input element.

Your issue and the library seem to be at cross purposes.  You might be able to work around it by detecting the underlying target of your click in js and then using js to focus after the mouse up event triggers.

If you have any ideas, I’m open to suggestions.

**Comment by kranthitechie** [comment]
Hi. Thanks for writing back.
Will try this and see how it works out :)

**Comment by markrcummins** [comment]
Any update to this issue? Facing the same problem with trying to select text in a quill text editor inside a pan zoom component.
