### ISSUE TITLE
Not working on touch devices and mobile emulation

### ISSUE THREAD

**Issue by ishaan-puniani** [KensingtonTech/ng2-panzoom#11]
Hello, 
nice library,
As the documentation mentioned that after 2.0 it had the support for mobile and touch.
Though I guess it has some issues or might be configuration that I am not able to find. 
On mobile is not coming up properly and when I adjust the container DRAGGING and pinch zoom stopped.
It is reproducible on the demo page as well (https://kensingtontech.github.io/ng2-panzoom-demo/)

![image](https://user-images.githubusercontent.com/2558553/61991066-641a6d00-b04b-11e9-90e7-d8ab3af1be9b.png)

this is how it is coming up. No pinch zoom, no drag for movement

**Comment by KensingtonTech** [comment]
Whilst some effort has been undertaken to support mobile, it is by no means complete nor fully supported.  I can confirm it works to some extend on mobile Safari on my own iPhone and iPad, but it is buggy at best.

I developed this library for a web application for which mobile support was not a requirement.  To be transparent, life does not permit me to devote much time to improving mobile support in the near to medium future, but if mobile support is what you require, you may wish to look elsewhere.

I am open to pull requests, though, if others are willing to make contribute.
