### ISSUE TITLE
Panning on touch devices

### ISSUE THREAD

**Issue by peeleto** [KensingtonTech/ng2-panzoom#13]
Hello, this is my first post on git-hub as a signed up member, so I'm new with this posting issues thing, sorry in advance. 
This library is great and I've implemented pan-zoom on my project, and it works as expected on the browser. But on a mobile device (using Ionic 4) the panning is the only thing that doesn't work when I drag my finger on the screen (on the computer browser when I drag the cursor pointer the panning is fine). Do you have any idea why is this happening?

**Comment by KensingtonTech** [comment]
Please refer to https://github.com/KensingtonTech/ng2-panzoom/issues/11

**Comment by zpydee** [comment]
I solved this requirement by setting `panOnClickDrag: false` and rather using Angular Material's cdkDrag for panning.
