### ISSUE TITLE
Keep in bounds and more

### ISSUE THREAD

**Issue by no12345678** [KensingtonTech/ng2-panzoom#15]
So i'm using the keep in bounds option and when the object i'm showing (a chart) is overflowing, i can't drag the part that's outside of the bounds. When i don't use the keep in bounds option- it works great, but the user can get the whole chart off the screen by dragging it out of the bounds- is it possible to know when the whole object is out of the bounds so i can trigger a function to reset the view?
Also, is there a way to know if some part of my object is out of the bounds? (i want to give the user an indication of that so he can know that there are more parts he can't see and can see if he would drag it).

**Comment by KensingtonTech** [comment]
Apologies for the extremely long delay in responding -- not sure whether you worked it out or not.  Off the top of my head, the best I can suggest is to subscribe to modelChanged and calculate the overflown size of your object and then do something when you calculate that it has gone out of bounds.

**Comment by KensingtonTech** [comment]
I will close this with the parting thought that, why not simply adjust their containing frame so that they're no longer overflowing?
