### ISSUE TITLE
Jquery dependency

### ISSUE THREAD

**Issue by jkachhia** [KensingtonTech/ng2-panzoom#17]
It seems that Jquery should move to dependency rather then devDependency. As it cause issue while ngAfterViewInit call and would not found Jquery when we only install ng2-panzoom.

    this.jQueryFrameElement = $('.pan-zoom-frame');
    this.contentHeight = $('.zoomElement').children().height();
    this.contentWidth = $('.zoomElement').children().width();

Possible to remove this dependency of Jquery?

**Comment by KensingtonTech** [comment]
Have you installed jquery in your project with `npm install jquery`?
