### ISSUE TITLE
ERROR in ./node_modules/ng2-panzoom/fesm5/ng2-panzoom.js

### ISSUE THREAD

**Issue by vibhuti261185** [KensingtonTech/ng2-panzoom#18]
I have implemented this plugin with angularjs 7 version but it's creating problems while building mode.
Error:
ERROR in ./node_modules/ng2-panzoom/fesm5/ng2-panzoom.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined

**Comment by KensingtonTech** [comment]
Hi @vibhuti261185 - sorry for the long delay.  Did you work this out?  If not, you're most likely using version 9 of the library, compiled for Angular 9 / Ivy.  Try installing with `npm install ng2-panzoom@^8.0.0`, which I *think* should work with Angular 7.

Or you can update your Angular version to v9.x.

**Comment by KensingtonTech** [comment]
@vibhuti261185 do you wish to add anything to this issue?
