### ISSUE TITLE
Binding mouseup event on child element is making wrapper pan

### ISSUE THREAD

**Issue by sushiie** [KensingtonTech/ng2-panzoom#23]
I have a big wrapper where I am placing a lot of child elements (these again are having a nice bit of HTML). On each child I am having a mouse up to do certain action but after the mouse up panning is getting triggered and its kinda sticky (dont know how to specify that otherwise, please pardon). 

Please help me here. I have already tried plenty of things.
event.preventDefault(), event.stopPropagation().

Also, nice piece of art here(will call it Art only). This library makes plenty of nice features to be realised with ease.

**Comment by KensingtonTech** [comment]
@sushiie, sorry for the long delay.  Please see https://github.com/KensingtonTech/ng2-panzoom/issues/12 for a similar issue with the mouseup event, explaining the inherent problem and a possible course of action.

If after reading that you have any more questions / requests, feel free to add them here.
