### ISSUE TITLE
Needs to list JQuery as a dependency

### ISSUE THREAD

**Issue by DouglasLapsley** [KensingtonTech/ng2-panzoom#28]
In blank project after npm install via `npm i ng2-panzoom` if you just `ng serve` you get a dependency warning that juery is missing.    In the NPM page it lists the dependency in the description, but not in the dependencies tab: https://www.npmjs.com/package/ng2-panzoom

**Comment by KensingtonTech** [comment]
jQuery is a peer dependency, so you must install it yourself.  This is mentioned in the readme file.

**Comment by DouglasLapsley** [comment]
Yes I know.  My point is that it's not listed as a dependency in the NPM listing.  It is in the readme, but not in the tabbed area.  
![image](https://user-images.githubusercontent.com/15831662/88195577-1b829900-cc38-11ea-8fb8-0a556c82cfa3.png)

**Comment by KensingtonTech** [comment]
@DouglasLapsley -- it's because it's specified as a peer dependency in package.json, and quite intentionally.  As best as I can tell, only dependencies and devDependencies will show on npmjs.org.

**Comment by DouglasLapsley** [comment]
OK thanks.  Just thought you would want to know :)

**Comment by KensingtonTech** [comment]
@DouglasLapsley FYI, version 10 has just been released, which removes the jQuery dependency.

**Comment by DouglasLapsley** [comment]
Great stuff.  Looking forward to using it.  Thanks for the update.
