### ISSUE TITLE
Support for Angular 10

### ISSUE THREAD

**Issue by godly-devotion** [KensingtonTech/ng2-panzoom#31]
Thank you for this useful project. We are upgrading to Angular 10 and noticed that ng2-panzoom doesn't support it yet. Are there plans to introduce support for Angular 10?

```
warning " > ng2-panzoom@9.0.0" has incorrect peer dependency "@angular/common@>=9.0.0 < 10.0.0".
warning " > ng2-panzoom@9.0.0" has incorrect peer dependency "@angular/core@>=9.0.0 < 10.0.0".
warning " > ng2-panzoom@9.0.0" has incorrect peer dependency "tslib@^1.10.0".
```

**Comment by KensingtonTech** [comment]
Hi @godly-devotion.  Yes, I am planning a new release for Angular 10.  In the meantime, you should be able to safely ignore the peer dependency warning.

**Comment by KensingtonTech** [comment]
@godly-devotion FYI, version 10 is out now.  I shall go ahead and close this issue.
