### ISSUE TITLE
Wheel event issue after updating to v9.0.1

### ISSUE THREAD

**Issue by kd2801** [KensingtonTech/ng2-panzoom#32]
Hi @KensingtonTech . I was facing similar issue. I updated to version 9.0.1. There is another issue which I am facing. When I am zooming in and zooming out using pinch wheel event, entire screen is zooming in/out instead of the panzoom elements.

_Originally posted by @kd2801 in https://github.com/KensingtonTech/ng2-panzoom/issues/30#issuecomment-674653729_

**Comment by KensingtonTech** [comment]
This is a problem with your web app rather than the library.  There are HTML controls specific to various mobile browsers which disable the native pinch-zoom functionality.
