### ISSUE TITLE
Renderer instead of Renderer2 for Angular 2.4.10

### ISSUE THREAD

**Issue by jdsinh** [KensingtonTech/ng2-panzoom#5]
./node_modules/ng2-panzoom/lib/panzoom.component.d.ts:1:56 

node_modules/@angular/core/index"' has no exported member 'Renderer2'. Did you mean 'Renderer'?

I replaced Renderer2 with Renderer in node modules but that give me error in browser saying :+1: 

Can't resolve all parameters for PanZoomComponent: ([object Object], ?, [object Object])."

**Comment by KensingtonTech** [comment]
I haven't tested backwards compatibility much, but Angular 2 definitely isn't supported.  Why are you using such an old Angular implementation, if you don't mind me asking?
