### ISSUE TITLE
modelChanged returns a model that does not implement isPanning?

### ISSUE THREAD

**Issue by runette** [KensingtonTech/ng2-panzoom#6]
There seems to be a problem with the model returned by modelChanged - it does not seem to implement the isPanning flag. This means that I have to explicitly fetch the model to know if the pan has finished.

**Comment by KensingtonTech** [comment]
Hi @runette, this will be fixed within the next few days.

**Comment by KensingtonTech** [comment]
This is now fixed in version 1.1.0.  Feel free to open a new issue if you still have issues.
